# Makes hyprsunset do nothing to the screen by default
# Without this, the default applies some tint to the monitor
profile {
    time = 08:30
    identity = true
}

# autostart.lua launches hyprsunset so this evening profile applies on schedule.
profile {
    time = 21:00
    temperature = 3000
    gamma = 0.5
}
